export const ADMIN_USERS_QUERY_LIMIT = 500;
export const ADMIN_DASHBOARD_ORDERS_QUERY_LIMIT = 300;
export const ADMIN_GIFTCARD_CLAIMS_QUERY_LIMIT = 300;
export const ADMIN_ORDERS_QUERY_LIMIT = 200;
export const ADMIN_FEE_TRANSFERS_QUERY_LIMIT = 300;
export const ADMIN_WITHDRAWALS_QUERY_LIMIT = 200;
